version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
      - AWS_COGNITO_REGION='eu-east-1'
      - AWS_COGNITO_POOL_ID=${AWS_COGNITO_POOL_ID}
      - AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - AWS_GRAPHQL_URL=${AWS_GRAPHQL_URL}